apiVersion: v1
kind: Service
metadata:
  name: wishlists-service
spec:
  type: ClusterIP
  selector:
    app: wishlist-app
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
