apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: behave
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/categories: Testing
    tekton.dev/pipelines.minVersion: "0.17.0"
    tekton.dev/tags: integration, testing, behave
    tekton.dev/displayName: "Run Behave Tests"
    tekton.dev/platforms: "linux/amd64"
spec:
  workspaces:
    - name: source
  steps:
    - name: bdd-testing
      image: quay.io/rofrano/pipeline-selenium:latest
      workingDir: $(workspaces.source.path)
      env:
       - name: BASE_URL
         value: "https://wishlist-app-route-jay-goettelmann-nyu-dev.apps.sandbox-m4.g2pi.p1.openshiftapps.com/"
      script: |
        #!/bin/bash
        set -e
        echo "***** Installing dependencies *****"
        python -m pip install --upgrade pip wheel
        pip install -qr requirements.txt
        export PATH="$PATH:/home/vscode/.local/bin"
        echo "***** Running Tests *****"
        behave